Feature/login signup
FightPandemics/FightPandemics-android pull request #125
Opened 2020-10-12 13:49 UTC by FeryelLH

**What this PR does**: This PR is to create XML files for Edit Individual Account screens

**Which issue(s) this PR fixes**: This PR fixes the issue #120

Fixes #

**Special notes for reviewers**:

**Additional comments**:

2020-10-12 20:44 UTC, jaliquiel commented
Could you include screenshots of the XML files?

2020-10-12 22:27 UTC, FeryelLH commented
profile_setting_my_account.xml screenshot : 
![setting_my_account](https://user-images.githubusercontent.com/32556639/95795297-ed19d480-0ce1-11eb-94e9-eec6a8be48e3.PNG)

profile_change_goal_fragment.xml screenshot : 
![change_goal](https://user-images.githubusercontent.com/32556639/95795359-1175b100-0ce2-11eb-8980-17982e0988c8.PNG)

profile_location_fragment.xml screenshot with empty Recyclerview : 
![change_location](https://user-images.githubusercontent.com/32556639/95795435-3c600500-0ce2-11eb-975e-545c9074f044.PNG)

=> layout item to be used in the RecyclerView : profile_location_item.xml screenshot : 
![location_item](https://user-images.githubusercontent.com/32556639/95795532-76c9a200-0ce2-11eb-9e27-0662f81d087d.PNG)

2020-10-13 12:59 UTC, carl05 requested changes

2020-10-13 12:59 UTC, carl05 commented on profile_change_goal_fragment.xml
> +        android:id="@+id/img_donation_box"
I think we should use <Checkbox> component, see [this](https://material.io/develop/android/components/checkboxes) and [this](https://developer.android.com/guide/topics/ui/controls/checkbox). Also, we should use TextInputLayout for alignment purposes if it's possible with <CheckBox>.  You can check examples on Signin and Signup fragments. This applies to all checkboxes.

2020-10-13 12:59 UTC, carl05 commented on profile_change_goal_fragment.xml
> +        android:id="@+id/profile_donation_back_arrow"
We already have a file with the AppBar layout you just need to include the file like this.

![image](https://user-images.githubusercontent.com/6819641/95862447-51b44e00-0d39-11eb-960a-880a4db13f2c.png)

2020-10-13 12:59 UTC, carl05 commented on profile_change_goal_fragment.xml
> +        app:srcCompat="@drawable/ic_back_arrow" />
We already have a ic_back_arrow using svg file from Zeplin please always prefer to use svg instead of png and import it as a vector asset.

2020-10-13 12:59 UTC, carl05 commented on profile_location_fragment.xml
> +        app:layout_constraintStart_toStartOf="parent"
Use components instead of repeat this code.

2020-10-13 12:59 UTC, carl05 commented on profile_setting_my_account.xml
> +        app:srcCompat="@drawable/ic_back_arrow" />
Use component and include as mentioned before

2020-10-18 09:40 UTC, carl05 approved these changes
Nice work!

2020-10-18 09:42 UTC, merged

2020-10-18 11:13 UTC, FeryelLH commented
Thanks @carl05, @mayorJAY and @jaliquiel  for the review :) .

2020-10-18 12:11 UTC, carl05 commented
Thank you for your nice work.

I fixed some issues with color values.

Whenever you need to use a value from zeplin as colors or dimens you need
to check for the value on the project ( ctrl + shift + f for windows) if it
is already defined reuse it or if it's not defined create it.

On Sun, Oct 18, 2020, 8:13 AM FeryelLH <notifications@github.com> wrote:

> Thanks @carl05 <https://github.com/carl05>, @mayorJAY
> <https://github.com/mayorJAY> and @jaliquiel
> <https://github.com/jaliquiel> for the review :) .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FightPandemics/FightPandemics-android/pull/125#issuecomment-711152506>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABUA6ONPQOQQCDXUUENA4GLSLLEWPANCNFSM4SM2QPWQ>
> .
>