Settings XML
FightPandemics/FightPandemics-android pull request #127
Opened 2020-10-15 00:23 UTC by rajasgandhi

**What this PR does**: adds xml files for settings signed out and logged in screen

**Which issue(s) this PR fixes**: https://github.com/FightPandemics/FightPandemics-android/issues/117

Fixes #

**Special notes for reviewers**: none

**Additional comments**: none

2020-10-17 13:44 UTC, mayorJAY approved these changes
LGTM, although the ic_arrow_left will still be removed later during refactoring as we already have it in the Login module but it's not been merged

2020-10-18 15:11 UTC, rajasgandhi commented
Hi, thanks. I did not know about ic_arrow_left, but all it is is this:
![image](https://user-images.githubusercontent.com/26011435/96371970-36c34e80-112a-11eb-8176-e576f84cda2a.png)

2020-10-24 00:34 UTC, mayorJAY reviewed
@rajasgandhi Please attach screenshots of what this design looks like. Thanks

2020-10-24 01:52 UTC, rajasgandhi commented
Hi @mayorJAY here are the designs
![image](https://user-images.githubusercontent.com/26011435/97065208-b1003280-1571-11eb-904f-9b6d4e74ad12.png)

2020-10-26 14:14 UTC, carl05 requested changes

2020-10-26 14:14 UTC, carl05 commented on profile/src/main/res/layout/activity_logged_in.xml
> +        android:layout_marginStart="20dp"
use dimens.xml atribute

2020-10-26 14:14 UTC, carl05 commented on profile/src/main/res/layout/activity_logged_in.xml
> +        android:layout_marginTop="54dp"
use dimens.xml atribute

2020-10-26 14:14 UTC, carl05 commented on profile/src/main/res/layout/activity_logged_in.xml
> +        android:layout_height="484dp"
use dimens.xml atribute

2020-10-26 14:14 UTC, carl05 commented on profile/src/main/res/layout/activity_logged_in.xml
> +        android:layout_marginTop="99dp"
use dimens.xml atribute

2020-10-26 14:14 UTC, carl05 commented on profile/src/main/res/layout/activity_logged_in.xml
> +        android:layout_marginBottom="74dp"
use dimens.xml atribute check all files please

2020-10-26 14:14 UTC, carl05 commented on profile/src/main/res/menu/menu_profile.xml
> +        android:onClick=""
can we remove this line?

2020-10-28 18:36 UTC, rajasgandhi commented on profile/src/main/res/menu/menu_profile.xml
> +        android:onClick=""
yes we can

2020-11-12 12:24 UTC, carl05 commented
@

2020-11-12 12:25 UTC, carl05 commented
@rajasgandhi can you please update the repository with the suggestions?

2021-01-07 00:58 UTC, carl05 approved these changes

2021-01-07 00:58 UTC, merged