Feature Home : Edit/Delete Post screens
FightPandemics/FightPandemics-android pull request #129
Opened 2020-10-20 14:47 UTC by anurjalal

What this PR does:  **Create XML files for Edit/Delete Post screens**

Which issue(s) this PR fixes:

**Fixes #123**

Special notes for reviewers: none

Additional comments: none

**I'm testing button in runtime.**
**edit_delete_fragment.xml**  -   when delete button is pressed

![cek1](https://user-images.githubusercontent.com/30503340/96601691-794c7d00-131c-11eb-93ef-964dde865ea7.png)

**edit_delete_fragment.xml**  -  when no button is pressed

![cek2](https://user-images.githubusercontent.com/30503340/96601673-75205f80-131c-11eb-9e40-ab61de13c27a.png)

**delete_post_alert.xml**

![dialogue](https://user-images.githubusercontent.com/30503340/96601680-76518c80-131c-11eb-8f61-94ce1a0ea313.PNG)

**delete_post_feedback.xml**

![post_deleted](https://user-images.githubusercontent.com/30503340/96601687-7782b980-131c-11eb-82c2-72751d40819e.PNG)

2020-10-24 00:38 UTC, mayorJAY approved these changes

2020-10-26 14:04 UTC, carl05 requested changes
please solve comments

2020-10-26 14:04 UTC, carl05 commented on .idea/markdown-navigator-enh.xml
> +</project>
pls remove these files and check if .idea is on gitignore

2020-10-26 14:04 UTC, carl05 commented on .idea/codeStyles/Project.xml
>          <option name="CONTINUATION_INDENT_SIZE" value="4" />
pls remove these files and check if .idea is on gitignore

2020-10-26 14:04 UTC, carl05 commented on .idea/markdown-navigator.xml
> +  </component>
pls remove these files and check if .idea is on gitignore

2020-10-26 14:04 UTC, carl05 commented on home/src/main/res/layout/delete_post_alert.xml
> +    android:background="#6b000000">
use color.xml attribute values

2020-10-26 14:04 UTC, carl05 commented on home/src/main/res/layout/delete_post_alert.xml
> +        android:layout_height="192dp"
use dimens.xml

2020-10-26 14:04 UTC, carl05 commented on home/src/main/res/layout/edit_delete_fragment.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
use dimens and colors

2020-10-26 14:04 UTC, carl05 commented on home/src/main/res/layout/delete_post_feedback.xml
> +
use dimens and colors

2020-10-26 14:04 UTC, carl05 commented on home/src/main/res/layout/delete_post_alert.xml
> +</androidx.coordinatorlayout.widget.CoordinatorLayout>
use dimens and colors

2020-11-05 20:45 UTC, Osaigbovo commented
Hello Ahmad! Can you please delete this pull request and create it for the home-feed branch instead?

2020-11-05 20:45 UTC, closed without merging