Feature/login signup
FightPandemics/FightPandemics-android pull request #130
Opened 2020-10-25 01:36 UTC by FeryelLH

**What this PR does**: Create XML files for Edit Organisation Account screens

**Which issue(s) this PR fixes**:

Fixes #119 

**Special notes for reviewers**: I didn't add the location screens since they are the same screens merged from issue#125

**Additional comments**:none

setting_organisation_account.xml: 
![image](https://user-images.githubusercontent.com/32556639/97096841-be004d00-1669-11eb-8fa0-db018bfd54fd.png)

org_type_fragment.xml
![image](https://user-images.githubusercontent.com/32556639/97096869-3535e100-166a-11eb-9665-9cc5c5f572df.png)

industry_fragment.xml:
![image](https://user-images.githubusercontent.com/32556639/97096881-7ded9a00-166a-11eb-91b4-c18fac3129dc.png)

org_change_goal_fragment.xml:
![image](https://user-images.githubusercontent.com/32556639/97096895-bc835480-166a-11eb-95a1-3980a2494284.png)

email_fragment.xml:
![image](https://user-images.githubusercontent.com/32556639/97096901-dc1a7d00-166a-11eb-8ba8-730d1cc57f00.png)

2020-10-26 13:10 UTC, mbobiosio approved these changes

2020-10-26 13:53 UTC, carl05 approved these changes

2020-10-28 22:24 UTC, mayorJAY requested changes
@FeryelLH Please endeavor to resolve the merge conflicts. Thanks

2020-10-29 10:24 UTC, gzodx commented
before pushing next time try pull from dev branch to abel to catch merge conflict from your local machine

2020-10-30 22:58 UTC, closed without merging