XML files update
FightPandemics/FightPandemics-android pull request #135
Opened 2020-11-04 23:19 UTC by ag58884n

**What this PR does**: Added the XML files created that are required in the issue #126 

**Which issue(s) this PR fixes**: Created XML files for Edit Organization Profile.

Fixes #

**Special notes for reviewers**: The Back Button in the toolbar and the error texts in the Edit Text field in the pages can be added using the Kotlin file.

**Additional comments**:

2020-11-06 17:36 UTC, carl05 requested changes
please add hexadecimals to colors.xml and integers dp to size.xml

2020-11-06 17:47 UTC, carl05 commented
Please add values to dinens, colors and strings xml

On Fri, Nov 6, 2020, 2:09 PM Jose Li <notifications@github.com> wrote:

> @jaliquiel <https://github.com/jaliquiel> requested your review on: #135
> <https://github.com/FightPandemics/FightPandemics-android/pull/135>
> Feature/Edit Organization Profile.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#event-3968144743>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABUA6OJZ4CENMAORXCX42U3SOQUWBANCNFSM4TKUWABA>
> .
>

2020-11-07 01:41 UTC, jaliquiel commented on profile/src/main/res/layout/edit_organization_profile_description.xml
> +            android:textColor="#282828">
use colors.xml file

2020-11-07 01:41 UTC, jaliquiel commented on profile/src/main/res/layout/edit_organization_profile_links.xml
> +        android:layout_marginLeft="31dp"
Instead of marginLeft use marginStart, and for marginRight use marginEnd

2020-11-07 01:41 UTC, jaliquiel commented on profile/src/main/res/layout/edit_organization_profile_links.xml
> +            android:hint="Facebook URL"
Extract string resource

2020-11-07 01:41 UTC, jaliquiel commented on profile/src/main/res/layout/edit_organization_profile_links.xml
> +            android:hintSize="20dp"
I couldn't compile the code, because android studio was telling me that android:hint is an unknown attribute for TextInputEditText. After deleting it, my code compiled. Could you check if this happens to you too?

2020-11-07 01:41 UTC, jaliquiel commented on profile/src/main/res/layout/edit_organization_profile_description.xml
> +    <view
This view was giving me errors. Could you check again? I made it work with this but not sure this is what you want.
    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="#d7d7d7"
    />

2020-11-07 01:41 UTC, jaliquiel commented on profile/src/main/res/layout/edit_organization_profile_description.xml
> +    <view
![image](https://user-images.githubusercontent.com/36528546/98397867-de8ab880-2014-11eb-9960-18d1f084f20a.png)

2020-11-07 02:49 UTC, carl05 commented
Nice review Jose!

On Fri, Nov 6, 2020, 10:41 PM Jose Li <notifications@github.com> wrote:

> *@jaliquiel* commented on this pull request.
> ------------------------------
>
> In profile/src/main/res/layout/edit_organization_profile_description.xml
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#discussion_r518892798>
> :
>
> > +
> +    <androidx.appcompat.widget.Toolbar
> +        android:layout_width="match_parent"
> +        android:layout_height="wrap_content"
> +        android:background="#ffff">
> +        <androidx.appcompat.widget.AppCompatTextView
> +            android:layout_width="275dp"
> +            android:layout_height="wrap_content"
> +            android:text="Description"
> +            android:layout_marginTop="31dp"
> +            android:layout_marginBottom="21dp"
> +            android:layout_marginLeft="60dp"
> +            android:layout_marginRight="24dp"
> +            android:textStyle="bold"
> +            android:textSize="24dp"
> +            android:textColor="#282828">
>
> use colors.xml file
> ------------------------------
>
> In profile/src/main/res/layout/edit_organization_profile_links.xml
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#discussion_r518894203>
> :
>
> > +    </androidx.appcompat.widget.Toolbar>
> +
> +    <view
> +        android:layout_width="match_parent"
> +        android:layout_height="1dp"
> +        android:background="#d7d7d7">
> +    </view>
> +
> +    <com.google.android.material.textfield.TextInputLayout
> +        android:id="@+id/text_input_Facebook_URL"
> +        android:layout_width="match_parent"
> +        android:layout_height="wrap_content"
> +        app:errorEnabled="true"
> +        app:boxBackgroundColor="#f6f7fb"
> +        android:layout_marginTop="32dp"
> +        android:layout_marginLeft="31dp"
>
> Instead of marginLeft use marginStart, and for marginRight use marginEnd
> ------------------------------
>
> In profile/src/main/res/layout/edit_organization_profile_links.xml
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#discussion_r518894487>
> :
>
> > +    <com.google.android.material.textfield.TextInputLayout
> +        android:id="@+id/text_input_Facebook_URL"
> +        android:layout_width="match_parent"
> +        android:layout_height="wrap_content"
> +        app:errorEnabled="true"
> +        app:boxBackgroundColor="#f6f7fb"
> +        android:layout_marginTop="32dp"
> +        android:layout_marginLeft="31dp"
> +        android:layout_marginRight="35dp"
> +        android:textColorHint="#425af2"
> +        android:typeface="sans">
> +
> +        <com.google.android.material.textfield.TextInputEditText
> +            android:layout_width="match_parent"
> +            android:layout_height="wrap_content"
> +            android:hint="Facebook URL"
>
> Extract string resource
> ------------------------------
>
> In profile/src/main/res/layout/edit_organization_profile_links.xml
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#discussion_r518900852>
> :
>
> > +        android:id="@+id/text_input_LinkedIn_URL"
> +        android:layout_width="match_parent"
> +        android:layout_height="wrap_content"
> +        app:errorEnabled="true"
> +        app:boxBackgroundColor="#f6f7fb"
> +        android:layout_marginLeft="31dp"
> +        android:layout_marginRight="35dp"
> +        android:layout_marginTop="24dp"
> +        android:textColorHint="#425af2"
> +        android:typeface="sans">
> +
> +        <com.google.android.material.textfield.TextInputEditText
> +            android:layout_width="match_parent"
> +            android:layout_height="wrap_content"
> +            android:hint="LinkedIn URL"
> +            android:hintSize="20dp"
>
> I couldn't compile the code, because android studio was telling me that
> android:hint is an unknown attribute for TextInputEditText. After deleting
> it, my code compiled. Could you check if this happens to you too?
> ------------------------------
>
> In profile/src/main/res/layout/edit_organization_profile_description.xml
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#discussion_r518906893>
> :
>
> > +        <androidx.appcompat.widget.AppCompatTextView
> +            android:layout_width="275dp"
> +            android:layout_height="wrap_content"
> +            android:text="Description"
> +            android:layout_marginTop="31dp"
> +            android:layout_marginBottom="21dp"
> +            android:layout_marginLeft="60dp"
> +            android:layout_marginRight="24dp"
> +            android:textStyle="bold"
> +            android:textSize="24dp"
> +            android:textColor="#282828">
> +
> +        </androidx.appcompat.widget.AppCompatTextView>
> +    </androidx.appcompat.widget.Toolbar>
> +
> +    <view
>
> This view was giving me errors. Could you check again? I made it work with
> this but not sure this is what you want.
> ------------------------------
>
> In profile/src/main/res/layout/edit_organization_profile_description.xml
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#discussion_r518907302>
> :
>
> > +        <androidx.appcompat.widget.AppCompatTextView
> +            android:layout_width="275dp"
> +            android:layout_height="wrap_content"
> +            android:text="Description"
> +            android:layout_marginTop="31dp"
> +            android:layout_marginBottom="21dp"
> +            android:layout_marginLeft="60dp"
> +            android:layout_marginRight="24dp"
> +            android:textStyle="bold"
> +            android:textSize="24dp"
> +            android:textColor="#282828">
> +
> +        </androidx.appcompat.widget.AppCompatTextView>
> +    </androidx.appcompat.widget.Toolbar>
> +
> +    <view
>
> [image: image]
> <https://user-images.githubusercontent.com/36528546/98397867-de8ab880-2014-11eb-9960-18d1f084f20a.png>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/FightPandemics/FightPandemics-android/pull/135#pullrequestreview-525347540>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABUA6ONIK7HHJI5FSHCQKFDSOSQUJANCNFSM4TKUWABA>
> .
>

2021-01-07 00:47 UTC, carl05 approved these changes

2021-01-07 00:50 UTC, jaliquiel approved these changes

2021-01-07 00:53 UTC, merged